Document: launchkey-ssh
Title: Debian launchkey-ssh Manual
Author: <insert document author here>
Abstract: This manual describes what launchkey-ssh is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/launchkey-ssh/launchkey-ssh.sgml.gz

Format: postscript
Files: /usr/share/doc/launchkey-ssh/launchkey-ssh.ps.gz

Format: text
Files: /usr/share/doc/launchkey-ssh/launchkey-ssh.text.gz

Format: HTML
Index: /usr/share/doc/launchkey-ssh/html/index.html
Files: /usr/share/doc/launchkey-ssh/html/*.html
